# Generated by Django 5.0.3 on 2024-03-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default/profile.png', upload_to='images/profile/')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=6)),
                ('address', models.CharField(blank=True, max_length=125)),
                ('city', models.CharField(blank=True, max_length=63)),
                ('phone', models.CharField(blank=True, max_length=18)),
                ('level', models.SmallIntegerField(choices=[(0, 'Magang'), (1, 'Outsource'), (2, 'Training'), (3, 'Junior Staff'), (4, 'Staff'), (5, 'Senior Staff'), (6, 'Junior Manager'), (7, 'Manager'), (8, 'Senior Manager'), (9, 'Junior Director'), (10, 'Director'), (11, 'Senior Director'), (12, 'Owner')], default=4, verbose_name='level')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='date of birth')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
